<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ExampleDevice" Id="{6a02f6dc-2c7b-486a-91fb-759c6a7468c4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ExampleDevice EXTENDS FB_Device
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ExampleDevice">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>